/**
 * The corpus root digest, compiled into the package.
 *
 * GENERATED by `pnpm corpus:seal`. Do not hand-edit — CI recomputes it.
 *
 * This constant is the anchor that makes the seal non-circular. `vectors/conformance/corpus-seal.json`
 * carries the per-file digests and per-area counts, but it travels WITH the corpus, so anything able to
 * truncate the corpus is able to re-seal it. The value below ships inside the package instead, so a
 * truncated tree fails against the runner's own expectation rather than against its own restated one.
 */
export const CORPUS_ROOT =
  "812149dbe956183ab87b923c636fb4c4f021f85bdc4f41d914a99c25117afead";
