/**
 * The corpus root digest, compiled into the package.
 *
 * GENERATED by `pnpm corpus:seal`. Do not hand-edit — CI recomputes it.
 *
 * This constant is the anchor that makes the seal non-circular. `vectors/conformance/corpus-seal.json`
 * carries the per-file digests and per-area counts, but it travels WITH the corpus, so anything able to
 * truncate the corpus is able to re-seal it. The value below ships inside the package instead, so a
 * truncated tree fails against the runner's own expectation rather than against its own restated one.
 */
export const CORPUS_ROOT =
  "ec4ad1b02a81538bab41919e630c3b232607ad440c7ff3d25c5f126e209011c8";
