/**
 * Seal the conformance corpus.
 *
 * The runner used to have no way to know whether it had been handed the whole corpus. `report.skipped`
 * derives from the same manifest a truncation would edit, so a shrunken corpus reported fewer passes, zero
 * skips, and exit 0 — a certifier silently certifying against a subset. The only real pin, 826 in
 * `test/runner.test.ts`, ships to nobody.
 *
 * The seal closes that in two layers, and the split is the whole point:
 *
 *  1. **Per-file digests and per-area case counts**, written here into `vectors/conformance/corpus-seal.json`.
 *     They make a failure LEGIBLE — "area X, file Y: expected 31 cases, found 27" rather than "digest
 *     mismatch". A bare root hash detects everything and diagnoses nothing.
 *  2. **A root digest over the sorted entries**, written here into `packages/conformance/src/corpus-root.ts`
 *     so it compiles INTO the shipped package. This is the anchor. A seal stored only beside the corpus is
 *     circular: whatever edits the corpus can edit the seal. The compiled constant lives where a corpus edit
 *     cannot reach it, so the two must be tampered with together, and doing that means editing the package
 *     itself — which is what npm provenance attests.
 *
 * Raw bytes, not canonicalized JSON: a reformat SHOULD invalidate the seal, and re-sealing is one command.
 * Canonicalizing here would mean a second JCS implementation whose disagreement with `report.ts`'s would be
 * invisible until it mattered.
 *
 * `--check` recomputes and exits non-zero on any drift, without writing. That is the CI gate; without it
 * the seal is a number someone has to remember to update, which is how the mutation ratchet would have
 * rotted too.
 */
import { createHash } from "node:crypto";
import {
  existsSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join, relative } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const VECTORS = join(root, "vectors");
const SEAL_REL = "conformance/corpus-seal.json";
const SEAL = join(VECTORS, SEAL_REL);
const ANCHOR = join(root, "packages/conformance/src/corpus-root.ts");

const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");

/** Every JSON file in the corpus, sorted — not just the manifest's areas. A truncation aimed at a schema
 *  file is the same attack as one aimed at a case file, and "only what the manifest lists" would leave the
 *  schemas unsealed while looking complete. */
function corpusFiles(dir = VECTORS, acc = []) {
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) corpusFiles(full, acc);
    else if (entry.endsWith(".json")) acc.push(full);
  }
  return acc;
}

const manifest = JSON.parse(
  readFileSync(join(VECTORS, "conformance/corpus-manifest.json"), "utf8"),
);
/** area id → case count, so a truncation INSIDE one area file is named rather than merely detected. */
const caseCounts = Object.fromEntries(
  manifest.areas.map((a) => [
    a.id,
    JSON.parse(readFileSync(join(VECTORS, a.file), "utf8")).cases.length,
  ]),
);

const files = corpusFiles()
  .filter((f) => f !== SEAL) // the seal cannot digest itself
  .map((f) => ({
    path: relative(VECTORS, f).split("\\").join("/"),
    sha256: sha256(readFileSync(f)),
  }));

/** The root: one line per file, plus one per area count, plus the totals. Newline-joined and hashed. The
 *  entries are already sorted by path; the area lines are sorted by id. Nothing here depends on how the
 *  seal file itself is formatted, so re-serializing the seal cannot change the root. */
function computeRoot(files, counts, totals) {
  const lines = [
    ...files.map((f) => `file ${f.path} ${f.sha256}`),
    ...Object.keys(counts)
      .sort()
      .map((id) => `area ${id} ${counts[id]}`),
    `totals ${totals.areas} ${totals.cases}`,
  ];
  return sha256(lines.join("\n"));
}

const totals = {
  areas: manifest.areas.length,
  cases: Object.values(caseCounts).reduce((a, b) => a + b, 0),
};
const seal = {
  $comment:
    "Generated by `pnpm corpus:seal` — do not hand-edit. `root` is also compiled into the conformance " +
    "package (src/corpus-root.ts); a corpus edit that updates this file but not that constant reads as " +
    "inauthentic, which is the point of keeping the anchor outside the tree it seals.",
  root: computeRoot(files, caseCounts, totals),
  totals,
  areas: Object.keys(caseCounts)
    .sort()
    .map((id) => ({ id, cases: caseCounts[id] })),
  files,
};

const anchor = `/**
 * The corpus root digest, compiled into the package.
 *
 * GENERATED by \`pnpm corpus:seal\`. Do not hand-edit — CI recomputes it.
 *
 * This constant is the anchor that makes the seal non-circular. \`vectors/conformance/corpus-seal.json\`
 * carries the per-file digests and per-area counts, but it travels WITH the corpus, so anything able to
 * truncate the corpus is able to re-seal it. The value below ships inside the package instead, so a
 * truncated tree fails against the runner's own expectation rather than against its own restated one.
 */
export const CORPUS_ROOT =
  "${seal.root}";
`;
// The line break above is not cosmetic drift: a 64-char digest puts this declaration over the formatter's
// width, so emitting it on one line makes `pnpm lint` fail on a file nobody edited. Generated output has to
// be born formatted, or every re-seal costs a manual fix-up.

/**
 * The live documentation quotes the runner's own output — `corpus: 44/44 areas, 832/832 cases, root
 * 20d44f8c…` — and those figures rot silently every time the corpus moves. They had, by 20 cases and a
 * whole root digest, and a reader following the guide would have compared their correct run against a
 * number the docs got wrong and concluded their install was broken.
 *
 * So the seal, which is the source of truth for all three, checks them. Scope is the LIVE documentation
 * only: `docs/developer/**`, the package READMEs and the root README. Dated records under `docs/` are
 * measurements taken on their date — rewriting those would turn a history into a lie — and this walk
 * never opens them.
 *
 * KNOWN FALSE POSITIVE, and it is the safe direction. The prose patterns match on shape, so a sentence in
 * scope reading "we triaged 40 cases across 3 areas" fails this gate. Inside `docs/developer/` and the
 * READMEs that phrasing is almost certainly about the corpus, and the failure names the file and line —
 * a false RED that diagnoses itself, never a false green. Reword the sentence if you hit it.
 */
const LIVE_DOCS = [
  join(root, "docs/developer"),
  join(root, "README.md"),
  ...readdirSync(join(root, "packages"))
    .map((d) => join(root, "packages", d, "README.md"))
    .filter((f) => existsSync(f)),
];

function markdownFiles(target, acc = []) {
  if (!existsSync(target)) return acc;
  if (statSync(target).isDirectory()) {
    for (const entry of readdirSync(target).sort())
      markdownFiles(join(target, entry), acc);
  } else if (target.endsWith(".md")) acc.push(target);
  return acc;
}

/** Stale corpus figures quoted in the live docs, as `<file>:<line>  <what>` strings. */
function staleCorpusFigures(totals, rootDigest) {
  const out = [];
  const shortRoot = rootDigest.slice(0, 16);
  for (const target of LIVE_DOCS)
    for (const file of markdownFiles(target)) {
      const lines = readFileSync(file, "utf8").split("\n");
      for (let i = 0; i < lines.length; i++) {
        const where = `${relative(root, file)}:${i + 1}`;
        // `corpus: 44/44 areas, 812/812 cases, root 149de2a398ea3ead… (authentic)`
        const provenance = /corpus:\s*(\d+)\/(\d+)\s+areas,\s*(\d+)\/(\d+)\s+cases,\s*root\s+([0-9a-f]+)/.exec(
          lines[i],
        );
        if (provenance !== null) {
          const [, a1, a2, c1, c2, quoted] = provenance;
          if (Number(a1) !== totals.areas || Number(a2) !== totals.areas)
            out.push(`${where}  areas ${a1}/${a2}, tree has ${totals.areas}`);
          if (Number(c1) !== totals.cases || Number(c2) !== totals.cases)
            out.push(`${where}  cases ${c1}/${c2}, tree has ${totals.cases}`);
          if (!rootDigest.startsWith(quoted))
            out.push(`${where}  root ${quoted}…, tree computes ${shortRoot}…`);
        }
        // `conformance: 812 passed, 0 failed, 0 skipped (none)` — only the UNNARROWED run is pinned; a
        // `--phase` sample legitimately reports fewer, and its own skip list names what it left out.
        const full = /conformance:\s*(\d+)\s+passed,\s*0\s+failed,\s*0\s+skipped\s*\(none\)/.exec(
          lines[i],
        );
        if (full !== null && Number(full[1]) !== totals.cases)
          out.push(`${where}  full run ${full[1]} passed, corpus holds ${totals.cases}`);
        // The prose restatements of the same number. These rotted independently of the pinned lines above
        // — one page said 823 in three sentences while the code fence beside them said 812.
        for (const re of [
          /(\d+) (?:registered )?cases across \d+ areas/,
          /of the (\d+) (?:registered )?cases/,
          /whether (\d+) cases ran/,
        ]) {
          const m = re.exec(lines[i]);
          if (m !== null && Number(m[1]) !== totals.cases)
            out.push(`${where}  prose says ${m[1]} cases, corpus holds ${totals.cases}`);
        }
      }
    }
  return out;
}

const check = process.argv.includes("--check");
if (check) {
  const onDisk = JSON.parse(readFileSync(SEAL, "utf8"));
  const anchorOnDisk = readFileSync(ANCHOR, "utf8");
  const problems = staleCorpusFigures(totals, seal.root);
  if (onDisk.root !== seal.root)
    problems.push(
      `corpus-seal.json root is stale: has ${onDisk.root.slice(0, 16)}…, tree computes ${seal.root.slice(0, 16)}…`,
    );
  if (!anchorOnDisk.includes(`"${seal.root}"`))
    problems.push(
      `src/corpus-root.ts CORPUS_ROOT is stale: tree computes ${seal.root.slice(0, 16)}…`,
    );
  if (problems.length > 0) {
    console.error(
      `corpus seal DRIFT:\n  ${problems.join("\n  ")}\n\n` +
        `A seal or anchor line is fixed by \`pnpm corpus:seal\`; a docs/ line is fixed by editing the doc to\n` +
        `quote a real run. The corpus is the source of truth for both, which is why one gate holds them.`,
    );
    process.exit(1);
  }
  console.log(
    `corpus seal OK — ${totals.areas} areas, ${totals.cases} cases, ${files.length} files, root ${seal.root.slice(0, 16)}…`,
  );
} else {
  writeFileSync(SEAL, `${JSON.stringify(seal, null, 2)}\n`);
  writeFileSync(ANCHOR, anchor);
  console.log(
    `sealed ${totals.areas} areas, ${totals.cases} cases, ${files.length} files — root ${seal.root.slice(0, 16)}…`,
  );
}
