import type { PlacementManifest } from "@integraledger/lcp-binding-core";

/**
 * A2A (Agent-to-Agent Protocol) reference placement — task metadata.
 *
 * Cut against the LIVE A2A specification: `specification/a2a.proto` in `a2aproject/A2A` at commit `0ef1b02`,
 * plus `docs/specification.md`, `docs/topics/extensions.md` and
 * `docs/topics/extension-and-binding-governance.md` at the same commit. Gate discharged 2026-07-30 and
 * reconciled against LCP v1.37 §C.8 the same day and re-checked against v1.38 §C.8 on 2026-08-08 — see the README for the discharge, the ONE drift it found
 * in the appendix (`AgentExtension` has a fourth field, `description`), and why §C.8's "not expected to be
 * dereferenced" sentence is NOT a drift: the host states it verbatim for its own official URI namespace, and
 * the hosted-specification line elsewhere in A2A's docs is SHOULD-level publication guidance for an author's
 * own URI, not an obligation.
 *
 * `0ef1b02` is `main`, dated 2026-07-23. It is NOT the `v1.0.1` tag: that release is 2026-05-28 and points at
 * `3303592`, two months earlier, and the trees differ — `AgentInterface.url`'s comment was reworded at
 * proto 337 to admit a gRPC `host:port` address, which shifts every later line by one. **Every proto line
 * number cited here and in the README is `0ef1b02`'s**, so reading them against the tag lands one line short.
 *
 * **Tier A.** The proto declares `google.protobuf.Struct metadata = 6` on `Task`, commented "A key/value
 * object to store custom metadata about a task", with no reserved keys and no constraint on values beyond
 * JSON validity. So the reference rides it with no coordination at all. §8.3.7: A2A is a connectivity
 * transport that settles nothing, so there is no settlement to bind into and no stronger pattern to claim.
 *
 * It is deliberately NOT §8.3.6 `protocol-extension`, on the same reasoning applied to ACP. A2A does have a
 * formal extensions framework, and anyone may publish an extension into it without upstream approval — but
 * §8.3.6 means the HOST protocol's own procedure is atrHash-aware, which no A2A implementation is, and it is
 * Tier B by definition, which would misdescribe a carrier that works today against stock A2A. Riding an
 * arbitrary metadata map is the weaker, undeclared, unnegotiated carrier; that is exactly why it works now.
 *
 * **camelCase is canonical here and snake_case is the alias — the reverse of ACP.** A2A's JSON wire is
 * proto3 lowerCamelCase throughout (`contextId`, `messageId`, `defaultInputModes`), so camelCase is the
 * host's own house style, and the host protocol's conventions decide — not a house rule of ours
 * and not LCP's appendix. The snake_case spelling is DECLARED because it is a real shape in the wild: the
 * proto field names are snake_case, and an implementer hand-writing JSON from the `.proto` emits that.
 * `encoding` is `reference-object` for the same class of reason: `metadata` is free-form, so nothing
 * constrains the shape, and the §8.1 object is what an implementer reading the spec would emit.
 *
 * **The container is `object-path`, NOT `header-map`.** A `Struct` is a JSON object and its keys are
 * case-SENSITIVE; the gRPC/HTTP transport metadata that carries an A2A call is the thing whose keys fold per
 * RFC 9110. Folding case here would accept a key A2A itself treats as a different key. A vector pins it.
 *
 * **One locator, EIGHT carriers.** The proto declares a `google.protobuf.Struct metadata` field on `Task`
 * (183), `Part` (236), `Message` (272), `Artifact` (290), `TaskStatusUpdateEvent` (304),
 * `TaskArtifactUpdateEvent` (321), `SendMessageRequest` (658) and `CancelTaskRequest` (723) — every one the
 * same free-form map under a different field number. That settles the write direction without a second
 * manifest: `Task.id` is generated by the server, so a client never writes `Task.metadata` — it writes the
 * `Message` it sends, the agent writes the `Task`, and the streaming path writes `TaskStatusUpdateEvent` and
 * `TaskArtifactUpdateEvent`. Every one of those ends uses this manifest unchanged, which is why it names a
 * path rather than a message type.
 *
 * **What this placement does NOT cover.** The Agent Card at `/.well-known/agent-card.json` declares, under
 * `capabilities.extensions[]`, what an agent REQUIRES of a counterparty before interacting — an
 * `AgentExtension` of `uri`, `description`, `required` and `params`. That is capability advertisement, not
 * the placement of a per-transaction reference, and it lives in `@integraledger/lcp-discovery`. It is not a
 * `readAlso` alias of this manifest at ANY carrier class, for two independent reasons: its `params` carry
 * REQUIREMENTS (`minimumLevel`, accepted jurisdictions, accepted dispute methods) rather than a reference to
 * a terms document, so there is nothing there for `extract` to decode; and it is a DIFFERENT DOCUMENT from
 * the one `place`/`extract` operate on, where ACP's and UCP's second carriers both sit in the same checkout
 * session. Two documents, two jobs — which is why `field` stays singular.
 *
 * **Declaration is not activation, and neither step touches this package.** A2A extensions "default to
 * being inactive"; a client activates by naming extension URIs in the `A2A-Extensions` request header, and
 * the agent's response SHOULD echo the set it activated. An Agent Card declaration alone is therefore never
 * exercised by any counterparty. The task-metadata carrier here needs neither step — it is live against
 * every conformant implementation with nothing negotiated — and that asymmetry is the whole argument for
 * placing the reference in `metadata` rather than behind an extension.
 *
 * **Limitation, stated plainly in the README:** custom metadata keys are interoperable only as far as the
 * receiving agent recognizes them, and nothing in A2A commits the value cryptographically.
 *
 * `carrierTypes` is the full §8.2 registry: `docs/specification.md` §3.2.5 says a metadata value "can be any
 * valid value that can be represented in JSON" and imposes no length budget, so narrowing the set would
 * invent a host constraint. Its consequence for `a2a/carrier-type-not-permitted` is worth stating,
 * because a reader will look for that arm and the two members do NOT behave alike. On `extract` it is
 * unreachable: a type the §8.2 registry does not define is not decoded at all, so the refusal is
 * `a2a/reference-malformed`, and every registered type is permitted here. On `place` it survives, reachable
 * only by a `ref` whose type is outside the registry — which TypeScript forbids at every call site, so the
 * arm exists for the untyped door. The conformance subject IS that door (it decodes `ref` out of JSON with no
 * runtime narrowing, as any non-TypeScript subject must), and a vector pins the arm there rather than leaving
 * it asserted-unreachable or manufacturing it by a narrowing the host does not ask for.
 *
 * `termsUrlFields` is omitted: A2A models no terms-URL field, and the manifest contract says an absent
 * `termsUrlFields` means a parser must not demand one.
 */
export const A2A_PLACEMENT: PlacementManifest = {
  protocol: "a2a",
  pattern: "http-advisory",
  tier: "A",
  encoding: "reference-object",
  container: { kind: "object-path" },
  field: "metadata.legalContext",
  // The alias inherits the manifest's `reference-object` encoding and needs none of its own — same payload,
  // same container, a different spelling. It is `integrity` by default (never declared as `discovery`),
  // because the class axis separates CARRIERS, not spellings: this is the reference field under a second
  // name, so it holds whatever that field holds — including a `url`, which `carrierTypes` permits and which
  // `readDeclaredPaths` labels `integrity` on the canonical path too. Declaring the alias `discovery` would
  // claim one slot weakens when spelled differently, which is false. It carries no `write` flag: writing both
  // spellings would put two copies of one fact on the wire and leave a reader to decide which is current.
  readAlso: [{ path: "metadata.legal_context" }],
  carrierTypes: ["sha256", "url", "ipfs", "ar"],
  specRef:
    "A2A Task.metadata, a free-form google.protobuf.Struct with no reserved keys (specification/a2a.proto at a2aproject/A2A@0ef1b02 — main 2026-07-23, after the v1.0.1 release; gate discharged 2026-07-30: see README)",
};
